# Generated by Django 4.1.4 on 2023-02-01 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0002_hashtag_article_saved_pic_alter_article_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='slug',
            new_name='tag_slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 17, 15, 30, 351525, tzinfo=datetime.timezone.utc)),
        ),
    ]
