# Generated by Django 4.1.4 on 2023-02-04 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0004_rename_title_hashtag_tag_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 21, 37, 5, 129674, tzinfo=datetime.timezone.utc)),
        ),
    ]
