# Generated by Django 4.1.4 on 2023-01-14 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0005_alter_article_date_alter_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 9, 51, 45, 636723, tzinfo=datetime.timezone.utc)),
        ),
    ]
