# Generated by Django 4.1.4 on 2023-01-23 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0009_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 17, 40, 46, 641296, tzinfo=datetime.timezone.utc)),
        ),
    ]
