# Generated by Django 4.1.4 on 2023-01-27 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0010_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 13, 58, 25, 152001, tzinfo=datetime.timezone.utc)),
        ),
    ]
