# Generated by Django 4.1.4 on 2023-01-27 14:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Articels', '0011_article_save_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 14, 10, 0, 381292, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='article',
            name='save',
        ),
        migrations.AddField(
            model_name='article',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
