# Generated by Django 4.1.4 on 2023-01-27 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0012_alter_article_date_remove_article_save_article_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 14, 38, 35, 974766, tzinfo=datetime.timezone.utc)),
        ),
    ]
