# Generated by Django 4.1.4 on 2023-01-27 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articels', '0014_alter_article_author_alter_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='save',
            new_name='saved_pic',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 17, 7, 15, 809102, tzinfo=datetime.timezone.utc)),
        ),
    ]
